### ISSUE TITLE
figcaption not centered with image

### ISSUE THREAD

**Issue by fkohrt** [cjquines/hexo-theme-ascent#12]
The following html (generated by [hexo-renderer-pandoc](https://github.com/wzpan/hexo-renderer-pandoc)) looks strange due to the figcaption not being centered while the image is.

```html
<figure>
    <img src="https://picsum.photos/500/300" alt="A random image">
    <figcaption>picsum.photos example</figcaption>
</figure>
```

**Comment by cjquines** [comment]
won't fix
