### ISSUE TITLE
My home page does not display "read more" button, and the full text is not abbreviated

### ISSUE THREAD

**Issue by yunbujian** [cjquines/hexo-theme-ascent#15]
Hi, your theme is really nice~ But I have a problem when reusing it...
 
My home page does not display the "read more" button, and the full text is not abbreviated，
This makes me very distressed. Do you know what's going on?

and by the way, The Archives time display overlaps. I don't know what to do...
Thank you for your time : )
![image](https://user-images.githubusercontent.com/59611117/154961304-ec579560-8962-4c29-bf7c-fc2b1e3d8a11.png)

**Comment by cjquines** [comment]
You have to use _config.yml to set `excerpt_length: 400` or something for "read more".

The Archive dates aren't supposed to be used with full dates, but you can add `.archive-article-date { width: fit-content; }`.
