### ISSUE TITLE
Archive Date Layout Problem

### ISSUE THREAD

**Issue by HanyuGao** [cjquines/hexo-theme-ascent#16]
Hi guys,

Thanks for this great theme! This is the most elegant one I've seen on GitHub!
I'm writing to ask about the **Date layout problem** in Archive, shown as below:
*(I have no coding background that I don't know whether it's a stupid question of my own, but I would really appreciate your help.)*

**Actual:**
![actual](https://user-images.githubusercontent.com/5299318/202656673-28784dc4-d718-4294-a6c5-3fe653fdf845.png)

**Expected:**
![Screen Shot 2022-11-18 at 12 22 05 AM](https://user-images.githubusercontent.com/5299318/202655381-64848d3f-4b98-425c-b688-7edc26aaf3d1.png)

Thank you!

**Comment by cjquines** [comment]
it should be related to this line:

https://github.com/cjquines/hexo-theme-ascent/blob/fbffb80729e72b4fe630b75b287b6966f72924d4/layout/_partial/archive-post.ejs#L4

**Comment by HanyuGao** [comment]
Thank you! CJ. 
I removed the line, and it seemed cleaner. However, what could I do if I wanted to re-edit the date_format?
I've tried date_format: 'DD‘ and preview locally, but it didn't work.

**Comment by cjquines** [comment]
i'm not sure, it might depend on your version :/ ?

**Comment by HanyuGao** [comment]
Theme version?
![image](https://user-images.githubusercontent.com/5299318/202840247-7f3f6bdd-4357-466f-95eb-a4644868e7f9.png)

**Comment by cjquines** [comment]
no, hexo version?

**Comment by HanyuGao** [comment]
After upgrading hexo to the latest version, changing the line that you pointed out still didn't work:

![Screen Shot 2022-11-19 at 5 21 42 PM](https://user-images.githubusercontent.com/5299318/202878221-096c8d48-7c68-45ac-828e-e579fab09471.png)

![Screen Shot 2022-11-19 at 5 20 54 PM](https://user-images.githubusercontent.com/5299318/202878209-dad8dc1c-2e67-4107-96d6-09bb0a2260e8.png)

**Comment by cjquines** [comment]
OH OKAY SORRY I JUST PUSHED A CHANGE AND IT SHOULD BE FIXED

**Comment by HanyuGao** [comment]
Thank you, CJ! It works.
