### ISSUE TITLE
Add mathematical formula display

### ISSUE THREAD

**Issue by barkure** [cjquines/hexo-theme-ascent#18]
Hello, this is the most concise and beautiful hexo theme I have ever seen. It is good in all aspects. 

But I want to insert a mathematical formula into the article, but it cannot be parsed and displayed correctly.😊

**Comment by cjquines** [comment]
have you tried the [hexo-math](https://github.com/hexojs/hexo-math) plugin?

**Comment by barkure** [comment]
it works, thank you!
